apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: atlantis
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.on-sync-succeeded.slack: "#team_母国語sql"
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/tosaken1116/spino_cup_2024
    path: infra/manifests/atlantis
    targetRevision: main
  syncPolicy:
    automated: {}
