apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-ingress
  namespace: argocd
  annotations:
    kubernetes.io/ingress.allow-http: "true"
    kubernetes.io/ingress.global-static-ip-name: spino-argo-static-ip-prod
    networking.gke.io/managed-certificates: argocd-cert
    ingress.gcp.kubernetes.io/redirect-http-to-https: "false"
    kubernetes.io/ingress.class: "gce"
spec:
  # ingressClassName: "gce"
  rules:
    - host: "argo.spino.kurichi.dev"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: argocd-server
                port:
                  number: 80
