name: "module-ci"
description: "install node_modules and cache them for later use"

runs:
  using: composite
  steps:
    - name: enable corepack
      run: corepack enable
      shell: bash
    - name: setup node
      uses: actions/setup-node@v4
      with:
        node-version: "20"
    - name: cache Dependencies
      id: cache-modules
      uses: actions/cache@v4
      with:
        path: frontend/node_modules
        key: ${{ runner.os }}-modules-${{ hashFiles('frontend/pnpm-lock.yaml') }}

    - name: Install Dependencies
      if: ${{ steps.cache-modules.outputs.cache-hit != 'true' }}
      run: |
        cd frontend
        pnpm install --frozen-lockfile
      shell: bash
