services:
  app:
    container_name: spino-cup-backend
    tty: true
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    ports:
      - 8080:8080
    develop:
      watch:
      - action: rebuild
        path: .
    depends_on:
      db:
        condition: service_healthy
    env_file: .env

  db:
    image: mysql:8.0
    container_name: spino-cup-db
    env_file:
      - .env
    hostname: ${DB_HOST:?err}
    expose:
      - ${DB_PORT:?err}
    environment:
      MYSQL_DATABASE: ${DB_NAME:?err}
      MYSQL_USER: ${DB_USER:?err}
      MYSQL_PASSWORD: ${DB_PASSWORD:?err}
      MYSQL_RANDOM_ROOT_PASSWORD: yes
      MYSQL_AUTHENTICATION_PLUGIN: caching_sha2_password
    volumes:
      - db-store:/var/lib/mysql
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
        ]
      interval: 1s
      timeout: 3s
      retries: 30

volumes:
  db-store:
