services:
  app:
    container_name: spino-cup-backend
    tty: true
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    ports:
      - 1323:1323
    volumes:
      - ./:/app
    depends_on:
      - db
    env_file: .env

  db:
    container_name: spino-cup-backend-db
    build:
      context: .
      dockerfile: docker/db/Dockerfile
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    volumes:
      - db-store:/var/lib/postgresql/data
    restart: always

volumes:
  db-store:
