apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: api
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/tosaken1116/spino_cup_2024
    path: infra/manifests/api
    targetRevision: main
  syncPolicy:
    automated: {}
