// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/tosaken1116/spino_cup_2024/backend/internal/app/config"
	"github.com/tosaken1116/spino_cup_2024/backend/internal/app/container"
	"github.com/tosaken1116/spino_cup_2024/backend/internal/router"
	"github.com/tosaken1116/spino_cup_2024/backend/pkg/database"
)

// Injectors from wire.go:

func New() (*container.App, error) {
	echo := router.New()
	dbConfig := config.NewDBConfig()
	databaseConfig := convertDBConfig(dbConfig)
	db, err := database.New(databaseConfig)
	if err != nil {
		return nil, err
	}
	app := container.New(echo, db)
	return app, nil
}

// wire.go:

func convertDBConfig(cfg *config.DBConfig) *database.Config {
	return &database.Config{
		DBHost:     cfg.DBHost,
		DBPort:     cfg.DBPort,
		DBName:     cfg.DBName,
		DBUser:     cfg.DBUser,
		DBPassword: cfg.DBPassword,
	}
}
