apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-cm
  namespace: opentelemetry
data:
  otel-collector-config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: "0.0.0.0:4317"
          http:
            endpoint: "0.0.0.0:4318"

    processors:
      batch: {}

    exporters:
      googlecloud:
        project: spino-cup-2024
        user_agent: "opentelemetry-collector"
        metric:
          prefix: "custom.googleapis.com/"
      debug:
        verbosity: detailed
    service:
      pipelines:
        metrics:
          receivers: [otlp]
          processors: [batch]
          exporters: [googlecloud, debug]
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [googlecloud, debug]
